### ISSUE TITLE
Crash on a map when calling the menu

### ISSUE THREAD

**Issue by Riccardoman** [stijn-volckaert/udemo#10]
![121518675-0ac64780-c9f1-11eb-8166-754565d70062](https://user-images.githubusercontent.com/74624503/121644484-55989b80-ca93-11eb-8141-8447cf5a3e4c.png)

Map JB-Construction-III

**Comment by SeriousBuggie** [comment]
Fixed here: OldUnreal/UnrealTournamentPatches/issues/534
