### ISSUE TITLE
Seekto is very slow and not accurate

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#100]
If your demo is long with a lot of players and action, the demo becomes "heavy" for the seekto command. If you use seekto with values such as 800 and beyond, you will notice how slow the seeking is as well as how inaccurate it is. The higher the value, the slower and more inaccurate the seek is.

To demonstrate this, I have made a quick example. In this clip I use "seekto 1400". You can see how slow the seeking is (it took around 12 seconds). When the seeking is done, notice what it says in the console - "Currently at 1412". That means there is 12 seconds of inaccuracy.

https://github.com/stijn-volckaert/udemo/assets/58362332/26a860cb-982b-4f19-8e34-bfd699e0c68d

This example is not as bad and it is somewhat acceptable. However, there are other mods like Siege, which are ten times more heavier with a lot of stuff going on, this results in a much longer seekto than a CTF game. A Siege game could take up to minutes, if you try to seekto with a value like 3000, it will take minutes to process the seek.

Here is the demo file from my CTF video example I showed, it has the needed files to play it back.
https://drive.google.com/file/d/1XreXNXMr84nhDif5o0duPzwKt0RUlmYU/view?usp=sharing

**Comment by SeriousBuggie** [comment]
Accuracy can be fixed.

Slow speed can't be fixed, only lightly improved. It cause by nature how seek work. Create all actors and apply all replicated info take time.
However sounds can be disabled, and some calls can be omitted. This can improve speed of seek in small amount.

**Comment by SeriousBuggie** [comment]
Profile during seek show 98% of load make Engine code, not demo driver itself:
![img](https://github.com/stijn-volckaert/udemo/assets/70026933/69d26034-3183-4fa7-8d0e-b9ee57ffe3a0)
