### ISSUE TITLE
No crouching in a demo

### ISSUE THREAD

**Issue by garry-ut99** [stijn-volckaert/udemo#103]
Just another funny bug in this unusable shit called "demo recording feature": a player is crouching in gameplay, but then when spectating the demo, he is standing instead.

**Comment by SeriousBuggie** [comment]
Demo not store info - crouch player or no. So technically impossible determine it precisely. However, possible some workaround by track current used animation. Such thing not precise, highly depends how properly implement player model and can be jumpy if during crouch show another anim, like `hit` or something else. 

Also if custom model not use for crouch animation group `Ducking` this not work too.

**Comment by SeriousBuggie** [comment]
Can't be solved even via track used animation.
Reason: `Ducking` animation group used during:
1. Rising:
```js
	BaseEyeHeight = 0.4 * Default.BaseEyeHeight;
	TweenAnim('DuckWlkS', 0.7);
```
2. PlayInAir:
```js
	if ( GetAnimGroup(AnimSequence) == 'Jumping' )
	{
		if ( (Weapon == None) || (Weapon.Mass < 20) )
			TweenAnim('DuckWlkS', 2);
		else
			TweenAnim('DuckWlkL', 2);
		return;
	}
	else if ( GetAnimGroup(AnimSequence) == 'Ducking' )
		TweenTime = 2;
	else 
		TweenTime = 0.7;
```
3. PlayDuck:
```js
	BaseEyeHeight = 0;
	if ( (Weapon == None) || (Weapon.Mass < 20) )
		TweenAnim('DuckWlkS', 0.25);
	else
		TweenAnim('DuckWlkL', 0.25);
```
4. PlayCrawling
```js
	BaseEyeHeight = 0;
	if ( (Weapon == None) || (Weapon.Mass < 20) )
		LoopAnim('DuckWlkS');
	else
		LoopAnim('DuckWlkL');
```

So there no any reliable way distinguish one from another. If reduce eye height each time when appear Ducking anim group it make shake on jumps and wrong eye height for rising.

Attempt track via TweenTime highly depends from sequence frames count and can't be used for determine which case where.

Also Animation is replication stuff, so stored not precise, some values can be skipped.
