### ISSUE TITLE
Can't delete a fucking demo

### ISSUE THREAD

**Issue by garry-ut99** [stijn-volckaert/udemo#104]
Issue similiar to (might be related or not, I dunno) :
- https://github.com/stijn-volckaert/udemo/issues/71

![delete_demo](https://github.com/stijn-volckaert/udemo/assets/72945564/04e53f9f-741d-41a7-a929-a21aed9a67ce)

Steps to reproduce using Mod > UDemo Manager GUI 3.5.1:
- A. Select demo X.
- B. Play demo X.
- C. Stop demo X.
- D. Press "DELETE" demo X - not works:
   - it says: "WARNING! FAILED TO REMOVE - Be sure that you are not currently playing this demo" 
   - no, I'm not playing the fucking demo because I already stopped it in step "C", see? 
   - Still not see? Go to an ophthalmologist.

Additional workaround steps which don't work either:
- E. Select a different demo Y
- F. Select again demo X
- G Press DELETE demo X - still not works

Finally, additional workaround steps which do work:
- E. Select a different demo Y
- F. Play demo Y
- G. Select again demo X
- H. Press DELETE demo X - it works

It seems it will refuse to delete demo X / unlock the demo X file, as long as another / differenet demo Y hasn't been played afterwards, only then the lock handle of demo X is released.

**Comment by SeriousBuggie** [comment]
Engine issue, not demo manager.

**Comment by SeriousBuggie** [comment]
Closed, since it goes to be: OldUnreal/UnrealTournamentPatches/issues/1290
