### ISSUE TITLE
Footstep sounds while crouch moving

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#109]
During demoplay - if you move while crouching, you can hear footstep sounds.

Demo file example:
[CrouchFootsteps.zip](https://github.com/stijn-volckaert/udemo/files/11833529/CrouchFootsteps.zip)

https://github.com/stijn-volckaert/udemo/assets/58362332/e38d643b-56b8-40bc-8673-f0c9a4862968

**Comment by SeriousBuggie** [comment]
Crouch not stored in demo. See #103 
So no any way distinguish it from usual walk.

**Comment by BerserkerBG** [comment]
> Crouch not stored in demo.

But if you look at the player model from 3rd perspective, you can see the model crouching

**Comment by SeriousBuggie** [comment]
Also model crouching during jumps for example. Same animation used in few places.
However possible in this case this detection can be used. During jump and wake up anyway no steps sound.
