### ISSUE TITLE
If you play a demo 1, then play demo 2, after resuming demo manager it will show demo 1 instead of 2

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#113]
This video will demonstrate the issue better:

https://github.com/stijn-volckaert/udemo/assets/58362332/ec162c15-5f3b-4c5c-a62a-b7c25d8f0844

When I play demo 1, I try to play demo 2 after. Then when I go back to demo manager I see demo 1 instead of demo 2.

**Comment by SeriousBuggie** [comment]
This happen because rypelcam load second copy of demo manager. Try delete LoadCam.int.

**Comment by BerserkerBG** [comment]
> This happen because rypelcam load second copy of demo manager. Try delete LoadCam.int.

Good catch
