### ISSUE TITLE
Hammer charge (loop) breaks during demoplay

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#12]
https://user-images.githubusercontent.com/58362332/135855415-4d44973f-1234-44c8-9275-de3dae784170.mp4

Both sound and visuals of the hammer are breaking, while charging. This is a long time issue present in every demo manager.

**Comment by SeriousBuggie** [comment]
Not able reproduce it.
Local play, no mods, v469d preview.


https://github.com/stijn-volckaert/udemo/assets/70026933/34c771b0-95b1-4222-837b-aa70c8afa109

**Comment by SeriousBuggie** [comment]
Can reproduce this issue if rec from client on dedic server.
