### ISSUE TITLE
Slomo makes Remaining Time inaccurate

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#120]
I used Slomo 100 at the beginning, then switched to Slomo 1 after pause. Notice the inaccuracy with the remaining time. About 5 seconds of inaccuracy from my example:

https://github.com/stijn-volckaert/udemo/assets/58362332/56d3912e-a072-4bee-8309-eab564cb9555

**Comment by SeriousBuggie** [comment]
`Slomo 100` is not really good candidate for tests. There can be very visible rounding errors. I think up to `slomo 10` must be preserve some kind of preciseness.
