### ISSUE TITLE
RypelCam "Roll" Rotation does not work

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#124]
![Screenshot_27](https://github.com/stijn-volckaert/udemo/assets/58362332/f78aeb18-47d9-440d-bb9f-b34c514cd463)
Roll rotation does not work with 469 udemo.

Here is an example of how the Roll rotation works (436 movie demo manager):

https://github.com/stijn-volckaert/udemo/assets/58362332/bc644c69-b71b-4881-862c-9792eb9db534

Here is the final animation with Roll rotations applied to all flags (436 movie demo manager):

https://github.com/stijn-volckaert/udemo/assets/58362332/f33eb5fc-2686-4bd6-9c2a-86a4a89b4a0f

**Comment by SeriousBuggie** [comment]
Udemo force reset Roll to zero, because sometimes during normal game, when you spectate other players, roll goes to non-zero which look as some bug.

However possible make exclusion for rypelcam and similar stuff.
