### ISSUE TITLE
Walking sounds while moving in the air

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#13]
https://user-images.githubusercontent.com/58362332/135855643-0eb725db-3f1a-407c-8bac-26c674e9e993.mp4

When you are moving around while you're in the air, the walking sound never stops. Longtime issue.

**Comment by BerserkerBG** [comment]
https://user-images.githubusercontent.com/58362332/135861745-a8e8bc49-6316-4fcd-80f3-ea94fd3f9f45.mp4

Strange sounds while moving in water, should be related to the same issue.

**Comment by garry-ut99** [comment]
Maybe a ghost. :D

**Comment by SeriousBuggie** [comment]
Clear run? Offline play? No any mods? Not able reproduce on latest test build:

https://github.com/stijn-volckaert/udemo/assets/70026933/c5eadfec-4277-44c1-ade5-692423bc8556

**Comment by BerserkerBG** [comment]
> Clear run? Offline play? No any mods? Not able reproduce on latest test build

Confirmed, its fixed in the latest 469d test release. Here is a demo:
[footsteps demo.zip](https://github.com/stijn-volckaert/udemo/files/11646330/footsteps.demo.zip)

When demo is played in 469c, I can hear footsteps in air. Water sound bug is also there. When you play the same demo in the latest test release, its fixed.

**Comment by SeriousBuggie** [comment]
Tested on attached demo. All as you say. v469c - affected, v469d - fixed. Issue can be closed.
