### ISSUE TITLE
Hud Messages with empty line between

### ISSUE THREAD

**Issue by prom6** [stijn-volckaert/udemo#149]
Normally they should all come after each other, line by line. (its not everytime but frequently)

![image](https://github.com/stijn-volckaert/udemo/assets/71797130/af12c556-7420-4abf-b344-cec5f211dcd0)

**Comment by SeriousBuggie** [comment]
Please post demo (with all related files), on which such happen.

**Comment by prom6** [comment]
Here you go. Couldnt find AnthCheckerC_v131 in my files (probably somewhere in cache but not listed in the .ini). I downloded the .uz file and put it in the package, hope thats ok.
[[fd_[-u-]]_CTF-IncineratorLE-102_[10_01_2006_2018]_[-u-]-morp.zip](https://github.com/stijn-volckaert/udemo/files/12506396/fd_.-u-._CTF-IncineratorLE-102_.10_01_2006_2018._.-u-.-morp.zip)

**Comment by SeriousBuggie** [comment]
This happen because of UTPure PureHitSound message.
It is fake message, which produce hit sound on client side.

I found there problems with play such hit sounds. Which manage to fix it. Possible it make difference of handle messages for warm up flags. However, this not remove empty line.

I even not sure if this empty line not appear in real play.
Did it appear in real gameplay?

**Comment by prom6** [comment]
Well the demo is quite old, I'm not 100 percent sure, but I would think this displayed correctly when I played back then. Also its Pure7G and I have several demos with Pure7G where the messages are displayed correctly (hitsounds were enabled on all of them) I can search for a demo that is Pure7G with hitsounds but the messages displaying correctly if that helps?

**Comment by SeriousBuggie** [comment]
Yea. Possible it helps.

**Comment by prom6** [comment]
Mh sorry I could have sworn its not on all demos, checked like 10 different ones from 2006 to 2010, all of them had it, just didnt notice before o_O
But I'm still pretty sure it didnt display like that when I played on the server back then. But when it has something to do with hitsounds, wouldnt the empty line show up more frequently? Or has the hit to be at a certain time to mess up the messages?

**Comment by SeriousBuggie** [comment]
It show each time when hit sound appear. But you see it only if there be message before and after.

I found fix which allow show more messages, and actually play this hit sound (as for now it not play).

Unfortunately I can't apply some dirty hack which filter this messages out, since it not only stop hit sound here, but can stop it in more fresh NewNet, which now work properly.

**Comment by prom6** [comment]
For me the hitsounds are working when playing the demo:

https://github.com/stijn-volckaert/udemo/assets/71797130/d52141f2-f2aa-4075-a4a5-9b757f2b7a16

if you got a fix but dont want to add it to the git, could you tell me? then i could add it to my version

**Comment by SeriousBuggie** [comment]
I will want test it for be sure it not goes bad. I will add it later.

Anyway it return back messages about double kill and possible affect other mods fix issues for it.

![Shot00643](https://github.com/stijn-volckaert/udemo/assets/70026933/6e108ea9-0d79-4679-a6cc-97bee36f75cf)
![Shot00642](https://github.com/stijn-volckaert/udemo/assets/70026933/024ebcb0-9ff8-4213-b0d5-86260da2ecdf)
![Shot00641](https://github.com/stijn-volckaert/udemo/assets/70026933/a6eb3f19-35cf-45ed-bef6-e49f6ff902e0)
![Shot00640](https://github.com/stijn-volckaert/udemo/assets/70026933/f8f12310-84c4-4793-b045-513591c61334)
![Shot00639](https://github.com/stijn-volckaert/udemo/assets/70026933/e86d48f6-a837-4c02-8b1d-f6cf0c6f06b8)
![Shot00638](https://github.com/stijn-volckaert/udemo/assets/70026933/5e209d78-f423-4956-832c-47a7ddd17147)
![Shot00637](https://github.com/stijn-volckaert/udemo/assets/70026933/56309f1c-9c51-4db3-b4cd-d86914870202)

Maybe it wrong. Need check for be sure.

**Comment by prom6** [comment]
your fix seems to work perfectly on my end, thanks
