### ISSUE TITLE
Seizures when you get killed

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#15]
https://user-images.githubusercontent.com/58362332/135862426-decab5f2-b67b-4a4b-ba1d-8408a8c8da4b.mp4

Every time you die or you get killed, the kill camera goes epileptic. The higher the framerate the worse it gets.

**Comment by SeriousBuggie** [comment]
Not able reproduce it. Did you play locally? Clean run without mods? On 400 FPS local play i not see such.


https://github.com/stijn-volckaert/udemo/assets/70026933/7907088a-606e-49b3-9712-1f01108b8618

**Comment by BerserkerBG** [comment]
> Not able reproduce it. Did you play locally? Clean run without mods? On 400 FPS local play i not see such.
> 
>  no_seizure.mp4

Yeah, you're right. Seems like its fine locally with no mods. The server is 91.224.117.101:7777 for reproduce, seems to be newnet issue.

**Comment by BerserkerBG** [comment]
https://github.com/stijn-volckaert/udemo/assets/58362332/211fa217-eb8b-4837-9aff-8cd595a4a3fc

This is live play vs demo play comparison, no mods. Notice how in live play when you die, you can cycle around your body in 3rd person. In demo play you can see that I enter first person inside my dead body. This could cause issues with some mods (like the original NewNet and other similar). My suggestion would be, in demo play when someone dies, switch to 3rd person spectate cam. Even if NewNet code is to blame for these seizures, I still think 3rd person spectate when someone dies is a needed feature and can potentially fix this issue on its own.

**Comment by SeriousBuggie** [comment]
What about stock demo driver? It too cause seizures? 

I try determine source of it. Or this caused by some action with demo driver do (or not do), or by info stored in demo itself.

**Comment by BerserkerBG** [comment]
> What about stock demo driver? It too cause seizures?

Good catch, stock demo driver has no seizures. udemo driver has seizures.

**Comment by SeriousBuggie** [comment]
Can you provide demo example with seizure after death? I want make few tests.

**Comment by BerserkerBG** [comment]
> Can you provide demo example with seizure after death? I want make few tests.

Yes, I just recorded a demo on PG servers, I've included the needed Ace files as well as the needed Cache files:
[SeizuresDemo.zip](https://github.com/stijn-volckaert/udemo/files/11994864/SeizuresDemo.zip)

**Comment by SeriousBuggie** [comment]
Did you see same seizure in game if input `behindview 0` immediately after death?

**Comment by BerserkerBG** [comment]
yes, it still happens

**Comment by SeriousBuggie** [comment]
This happen because of broken NewNet code.
On ViewShake it set ViewRotation to random value.
```unrealscript
	ViewRotation = RotRand(False);
//	ViewRotation.Yaw = -32768;
//	ViewRotation.Pitch = Rand(65536)-32768;
	ViewRotation.Roll = zzViewRotation.Roll; 
```
There even funny comments in other place:
```unrealscript
	ViewShake(deltaTime);		// ViewRotation is fuked in here.
	ViewFlash(deltaTime);
```
