### ISSUE TITLE
Demo with missing files crashes when opening Demo Manager twice

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#154]
Demo Manager crash on demo with missing files.

![Screenshot_284](https://github.com/user-attachments/assets/1203f2e7-df30-44bb-ae76-37d398110d5e)

https://github.com/user-attachments/assets/711a394b-bb50-4a82-b94e-2ebd76968375

Demo File: [CTF-BT-Adeon-Factory-II-RE2_Bunneh_126_781.zip](https://github.com/user-attachments/files/16487473/CTF-BT-Adeon-Factory-II-RE2_Bunneh_126_781.zip)

Reproduce steps:
1. Open Demo Manager
2. Select the demo with missing files
3. Close Demo Manager
4. Open Demo Manager
5. Play the demo

Result: Crash

**Comment by SeriousBuggie** [comment]
Engine problem, not udemo. Issue transferred into patch repo.
