### ISSUE TITLE
Enable 3rd person Free Floating during Pause

### ISSUE THREAD

**Issue by BerserkerBG** [stijn-volckaert/udemo#17]
If you playback a demo in 3rd Person spectate and Pause it, you will not be able to move around during pause.

![Screenshot_1914](https://user-images.githubusercontent.com/58362332/151668579-a2e88e51-836e-4261-8c1f-19616f0463f0.png)

**Comment by SeriousBuggie** [comment]
I think impossible do what you want, during nature of pause command - nothing ticked, include demoplay spectator, which move around on common basis. like any other actor and need be ticked for do this.

So it goes to be engine change, not udemo itself. 

But you can try use very low slomo, like 0.001 or less. After apply #50 it work pretty same as pause command, but you still able move around.  Possible it make different spectator movement speed on very low speeds, but 0.001 work pretty well as for me.

**Comment by BerserkerBG** [comment]
> I think impossible do what you want, during nature of pause command - nothing ticked, include demoplay spectator, which move around on common basis. like any other actor and need be ticked for do this.

But there is already an old demo manager called "moviedemomanager", which already does this. It does not work with 469, it will only work on 436. There is also moviedemomanager 1.1 version, you can find it on medor's site, it has a readme which can be helpful, but I can't seem to get moviedemomanager 1.1 to work - it crash even 436 UT.

Here is the moviedemomanager, I believe this is 1.0:
[moviedemomanager.zip](https://github.com/stijn-volckaert/udemo/files/11514865/moviedemomanager.zip)

This special demomanager will work only on 436. You need to enable Mouse Smoothing in order to move your mouse during pause. When you pause you can free float around the map, there is also no pause text.
