### ISSUE TITLE
Weaponhand bug/weird behaviour

### ISSUE THREAD

**Issue by prom6** [stijn-volckaert/udemo#22]
https://user-images.githubusercontent.com/71797130/209866941-0a0827a3-da4d-4657-b31e-8ce5a364b01c.mp4

I think it occurs on older demos, like from 2004 and older (Pure6E and before)

**Comment by prom6** [comment]
Probably found a track to it

Based on Anthrax' comments in the DemoPlaybackSpec.uc class, UTPure messes things up with Viewrotation

UTPure does this in bbPlayer.uc (bbPlayer extends TournamentPlayer):

```java
function xxFixDemoBug()
{
	if (Role==Role_Authority)
	{
		DemoViewPitch = zzViewRotation.Pitch;
		DemoViewYaw = zzViewRotation.Yaw;
	}
}

````

No idea why Pure does those weird viewrotation calculations in the first place and why it seemed to be a fix for demoplayback back then.

Anyway, when i comment out setting Role to Role_Authority in DemoPlaybackSpec.uc :

```java
// Temporarily set ViewTarget.Role to ROLE_AUTHORITY. This allows us to
        // call functions that only the server can usually call
        oldRole=PlayerPawn(ViewTarget).Role;
        //PlayerPawn(ViewTarget).Role=ROLE_AUTHORITY;
````

the weapon is rendered correctly.

I'm a noob in uscript, so...

- I guess the role_authority was given for a reason (by far beyond my knowledge :))
- I dont know if this breaks some other function or produces some other weird behaviour somewhere else (so far didnt notice any strange things in old and newer demos though)
- I dont know if there is a different/proper way to fix this, maybe the function in bbPlayer.uc can be overwritten with a function from udemo.u or it can be blocked somehow?

Maybe one of the contributors @stijn-volckaert can figure this out :o

edit: I guess the problem is somewhere else in the script, but something in the functions that are only executed on role authority is causing this behaviour

**Comment by SeriousBuggie** [comment]
> I think it occurs on older demos, like from 2004 and older (Pure6E and before)

Please upload some demos which show that and which able play now regular client (all packages can be downloaded from net or attached to demo file).

**Comment by prom6** [comment]
here is the demo from the short clip, with necessary files
[klgtraininfested10042004-allfiles.zip](https://github.com/stijn-volckaert/udemo/files/12177914/klgtraininfested10042004-allfiles.zip)

**Comment by SeriousBuggie** [comment]
If you among v469d testers - please test build 252.
If no - you can join to them. Go to OldUnreal discord and say to Anthrax your github login.
