### ISSUE TITLE
Recorded demos are unplayable/broken, a player does not move across/along the map, only stuck rotating in same place at the beginning.

### ISSUE THREAD

**Issue by garry-ut99** [stijn-volckaert/udemo#31]
Unable to play a f..king demo ! When playing locally demos recorded as a client on an online server, a player does not move across/along the map, only stuck rotating in same place at the beginning. It makes the whole udemo functionality broken and useless, and until it will be fixed, currently gameplay of ut need to be recorded using screen capture programs.

**Comment by SeriousBuggie** [comment]
Not sure if it related to udemo at all. Try play demo with usual driver
`DemoRecordingDevice=Engine.DemoRecDriver`
If result is same, then demo broken itself.

Demo is complicated thing. All used mods must be aware of it, or else all be ruined in demo. And this not udemo fault in such case.

For example early version of XVehicles not be aware of demo and produce bs on exit. All ruined. Latest version aware, and if my screen recs broken by some reason, I can rec it from demoplay, and this pretty good.

But anyway not expect 100% same view, ESP if used custom mods, HUDs, etc It is limitation of technology. it is not screen rec, it like more specate you by someone as spectator. Some things missed or work in different way.

**Comment by garry-ut99** [comment]
> Not sure if it related to udemo at all. Try play demo with usual driver
> `DemoRecordingDevice=Engine.DemoRecDriver`
> If result is same, then demo broken itself.

Demo recorded in stock demo plays fine in both stock demo driver and udemo driver.
Demo recorded with udemo plays fine in stock demo driver, but not in udemo driver.

Try to reproduce: use 469c client + udemo 3.5.1, join LONDON server as a spectator and then use `behindview 0`, then `demorec test`, then try to play the demo in udemo driver.

**Comment by SeriousBuggie** [comment]
Which one?
![img](https://github.com/stijn-volckaert/udemo/assets/70026933/580a08ee-130c-4f9d-9df8-1ac39926fffc)

**Comment by SeriousBuggie** [comment]
You talk about demo recorder from spectator. For look this demo you need use 3rd person view switch.

Or start it like `demoplay test?timebased?3rdperson`

Usual demo where you play recorded normally.

This difference caused by way which udemo used for play demos. It use Spectator which view who record demo.
If you spectator during recording demo, you really sit in one place and only rotate. It what you do.
Udemo not follow your ViewTarget, just look at you.

Usual demo, not use spectator, it operate same pawn, so you see ViewTarget. But this not allow you switch to another player and other extended features, which provide udemo.

**Comment by garry-ut99** [comment]
OK, I understand now, with 3rdperson option enabled, demos indeed play fine now! I'm happy now. 

But it was not my fault, because:
- this option is disabled by default
- and readme doesn't say anything about a need to enable it to play correctly demos recorded as a spectator, or is too hard to find / understand it
- so maybe it's worth to mention about it in readme

**Comment by SeriousBuggie** [comment]
I think it must be notice if udemo during parse found it be recorded from spectator. Or simple put this checkbox for such demo automatically on default.
