### ISSUE TITLE
smartctf stats not working with udemo.udemodriver

### ISSUE THREAD

**Issue by ANaPhOrAX** [stijn-volckaert/udemo#4]
They show up when I switch back to engine.demorecdriver, but if I use the udemodriver, they don't work.

I should note that the "mutate smartctf showstats" command does nothing (no error message either), and togglestats gives an "Unrecognized command" error.

If I use udemo.udemodriver and then type 'togglestats', it says "udemo couldn't spawn statsthingie". 'mutate smartctf showstats' just does nothing, also no error message, same as before.

Is there any chance you might be able to explain to me why this happens, and/or provide a fix in a future update? Or tell me why it's impossible to fix?

I'm using the UT99-1337 version from the PG discord, updated to 469 with the latest patch (16th of april).

**Comment by stijn-volckaert** [comment]
This will be fixed in the udemo version included in the upcoming v469 build. "mutate smartctf showstats" will still not get recognized, but "togglestats" should work.
