### ISSUE TITLE
Too many demo files crash UT

### ISSUE THREAD

**Issue by SeriousBuggie** [stijn-volckaert/udemo#46]
![udemo crash](https://github.com/stijn-volckaert/udemo/assets/70026933/4caa44ec-e00b-40ea-9d4f-8e6991a0a20a)
![Screenshot_2191](https://github.com/stijn-volckaert/udemo/assets/70026933/2ba3603f-3071-4c2e-b4e1-ae56e4a0bf97)
> when I launch UT and bring up xconsole
didnt change anything

> Note: The game starts but when I press Esc to show the menu it crashes with that error
Update: I cleaned up the Demo recording folder and it works now

1. Count of loaded demos must be limited, possible with warning.
2. Sorting must be optimized for reduce hit limit.

or

All things must be moved in native, where can be sorted more fast, and without any limits.

**Comment by SeriousBuggie** [comment]
There no way sort really huge lists on uscript side. Need move to native.
Even if used delayed tree sort, it fine only for first load list. Later it goes reload demos list and it goes O^2 way, so 5000 files for sure hit runaway limit.

**Comment by Chamberly** [comment]
I can confirm a lot of people having this issue. Once it get so many demo in the file or the size of it end up in the crash.
Thus, removing them or moving to another folder makes it playable again.
