### ISSUE TITLE
Suggestion: Sort in order by date

### ISSUE THREAD

**Issue by Chamberly** [stijn-volckaert/udemo#5]
Instead of digging through the alphabetical order of the demo, can we have it to be sorted by recent recorded date?

**Comment by SeriousBuggie** [comment]
As workaround - can be changed format of naming demo. Put date first.

But in general better implement ability switch order too.

**Comment by SeriousBuggie** [comment]
This can be done in UI like two buttons with label before

Order by: "Date" "Name"

Selection show as toggled button and preserve in config for use on next load.

Place - above combobox of demos (?)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1684673868](https://github.com/stijn-volckaert/udemo/assets/70026933/bbe6ddcd-a23f-47ec-803b-395765fbce29)

**Comment by SeriousBuggie** [comment]
After pending PRs will be resolved, possible make new PR from this commit: https://github.com/SeriousBuggie/udemo/commit/3bdcac8d24fe4f13156342c01180e75de7682067
which close this issue.
