### ISSUE TITLE
Udemo not picking up the right name for the POV player

### ISSUE THREAD

**Issue by J3FFmaster** [stijn-volckaert/udemo#7]
As mentioned on Discord, the demo manager always shows my currently set in-game username when watching demos (instead of the nick the POV-user had when the demo was originally recorded).

[2on2-gxp-mtw-deck.zip](https://github.com/stijn-volckaert/udemo/files/5479166/2on2-gxp-mtw-deck.zip)

**Comment by SeriousBuggie** [comment]
Look like issue already fixed.
v469d preview.
![Shot00497](https://github.com/stijn-volckaert/udemo/assets/70026933/bf768913-6daa-4777-b304-1cf9438de7b4)
